# Generated by Django 3.2.16 on 2023-02-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_getimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.DeleteModel(
            name='GetImage',
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
